name: Testing Task

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Testing Task
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Testing Task
        run: mvn -B test 
        